### ISSUE TITLE
Add docs for usage of co2js within the impact framework

### ISSUE THREAD

**Issue by alexzurbonsen** [thegreenwebfoundation/co2.js#216]
Hey Chris, hey everyone,
co2js is also available as a [plugin within the impact framework (IF)](https://github.com/Green-Software-Foundation/if-unofficial-plugins), a recent project by the Green Software Foundation. I have used it in an IF plugin to measure/estimate the carbon emissions of webpage loads. Would you be interested in making the connection to IF more visible, may be add usage hints etc. to make usage as simple as possible?
Best, Alex

**Comment by mrchrisadams** [comment]
hi @alexzurbonsen - yes, this would be great!

However, I'm not sure what files would need to stay inside the CO2 js repo to make this work, and I'd welcome some pointers from you.

When I look at the sample manifest file in your linked repo, it looks like the manifest file is doing two things:

1. declaring a bunch of plugins, one of which is co2.js

```yaml
name: measure-webpage-demo
description: example manifest for estimating carbon emissions of a webpage
tags:
initialize:
  outputs:
    - yaml
  plugins:
    "timer-start":
      method: TimerStart
      path: '@wr24-greenit/if-webpage-plugins'
    "timer-stop":
      method: TimerStop
      path: '@wr24-greenit/if-webpage-plugins'
    "green-hosting":
      method: GreenHosting
      path: '@wr24-greenit/if-webpage-plugins'
    "measure-webpage":
      method: MeasureWebpage
      path: '@wr24-greenit/if-webpage-plugins'
    "co2js":
      method: Co2js
      path: '@wr24-greenit/if-webpage-plugins'
      global-config:
        options:
          firstVisitPercentage: 0.9
          returnVisitPercentage: 0.1
```


2. And using some features of CO2.js in the plugins in a pipeline, once the earlier steps have worked out the total data transfer.

I think the `config` block is where you. have defined various params for calling each plugin in the pipeline - so for co2js, you're passing in the swd model, and this might be where you pass in further params for that pipeline stage.

Is this sort of how it works?


```yaml
tree:
  children:
    child:
      pipeline:
        - timer-start
        - measure-webpage
        - timer-stop
        - green-hosting
        - co2js
      config:
        co2js:
          type: swd
        measure-webpage:
          lighthouse: true
          scrollToBottom: true
      inputs:
        - timestamp: '2024-01-01T00:00:00Z' # will be replaced by the actual timestamp
          duration: 1 # will be replaced by the time it took to execute the measure-webpage plugin
          url: https://www.tngtech.com
          resets: [true] # tells the timer-stop method to replace timestamp and duration
```

I'm aware that whole manifest file contains plugins that do quite a lot, like running a full browser and so on - this would likely increase the size of the co2js library, and quite a lot of effort has gone into keeping the library small, as well as the number of dependencies low.

To keep this smalll to start off with, I wonder how much would be needed to extract `co2js` from the this repo as a first step so instead of needing to pull in a plugin like this:

```yaml
    "co2js":
      method: Co2js
      path: '@wr24-greenit/if-webpage-plugins'
```

You might have something like this, where in the pipeline it's acting as as wrapper that called some of the swd model functions by default:

```yaml
    "co2js":
      method: Co2js
      path: '@TGWF/co2js'
```

Would this be an ok experimental first step, to see how easy it might be to extend co2.js to work in impact framework pipelines?

it looks like the code that calls CO2js is in this part of the plugin repo:

https://github.com/wr24-greenit/if-webpage-plugins/tree/main/src/lib

This might also be nice way to support some of the new parameters that @fershad merged in recently that you mentioned were a bit harder to use until that change was made.

👍 ?

I'll wait for @fershad to chime in, as he's more familiar with CO2.js than I am these days, and I reckon he'd likely cast an eye over any PR made
